# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ee/ci/docker/using_docker_images.html#what-is-a-service
services:
#   - mysql:latest
  - redis:latest
  - postgres:latest

include:
  - template: Security/SAST.gitlab-ci.yml

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache
cache:
  paths:
    - back/node_modules/

before_script:
  - cd back

stages:
  - uni_test
  - sec_scan
  # - build

unit-test:
  stage: uni_test
  script:
    - yarn install
    - yarn run unit-test
    # - npm install
    # - node ./index.js
    # - node ./specs/start.js ./specs/async.spec.js

# yarn-audit:
#   stage: audit_scan
#   script:
#     - yarn audit

snyk-scan:
  stage: sec_scan
  script:
    - yarn global add snyk
    - snyk test

# test_db:
#   script:
#     - npm install
#     - node ./specs/start.js ./specs/db-postgres.spec.js

# build:
#   stage: build
#   script:
#     - npm eslint
#     - npm 