version: "3"

services:
  node:
    image: node:14
    # build: ./back
    user: node
    container_name: node-14
    working_dir: /usr/src/aws-vpc
    environment:
      NODE_ENV: test
      PORT: 4200
      PGHOST: postgres-10-8
      PGDB: michaeldemerjian
      PGUSER: michaeldemerjian
      PGPASS: payroll
      PGPORT: 5432
    networks:
      node_net:
        ipv4_address: 172.28.1.3
    command: yarn run start
    volumes:
      - .:/usr/src/aws-vpc
    ports:
      - "4200:4200"
    depends_on:
      - "postgresql"

  postgresql:
    image: postgres:10.8
    container_name: postgres-10-8
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: michaeldemerjian
      POSTGRES_PASSWORD: payroll
    networks:
      node_net:
        ipv4_address: 172.28.1.5
    volumes:
      - postgresql:/var/lib/postgresql
      - data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin-4
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@symply.com
      PGADMIN_DEFAULT_PASSWORD: payroll
    networks:
      node_net:
        ipv4_address: 172.28.1.6

volumes:
  postgresql:
  data:

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
